apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-smoke-tests-to-apps
  namespace: linuxspec-prod
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - linuxspec-frontend
          - linuxspec-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              purpose: smoke-test
