apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - allow-dns-egress.yaml
  - allow-ingress-controller.yaml
  - allow-smoke-tests.yaml
  - allow-prometheus-scrape.yaml
  - allow-frontend-to-backend.yaml
  - allow-backend-to-mongodb.yaml
  - allow-backend-egress-external.yaml
  - allow-frontend-egress-external.yaml
