apiVersion: v1
kind: Service
metadata:
  name: linuxspec-backend
  namespace: linuxspec-prod
  labels:
    app: linuxspec-backend
spec:
  type: ClusterIP
  selector:
    app: linuxspec-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
