apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linuxspec-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: api.linuxspec.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linuxspec-backend
                port:
                  number: 80
