apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linuxspec-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.linuxspec.com
      secretName: api-linuxspec-tls
  rules:
    - host: api.linuxspec.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linuxspec-backend
                port:
                  number: 80
    - host: web-test.linuxspec.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linuxspec-frontend
                port:
                  number: 80
