apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deployment.yaml
- backend-service.yaml
- configmap-secret.yaml
- fintech-ingress.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml
- postgres.yaml
images:
- name: ghcr.io/xilpanda/linuxspec-frontend
  newTag: 20eb9d4
- name: ghcr.io/xilpanda/linuxspec-backend
  newTag: 61cf483
