apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace-linuxspec-prod.yaml
- backend-alerts-prometheusrule.yaml
- backend-deployment.yaml
- backend-hpa.yaml
- backend-servicemonitor.yaml
- backend-service.yaml
- configmap-secret.yaml
- fintech-ingress.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- grafana-ingress.yaml
- ingress.yaml
- postgres.yaml
- security/network
images:
- name: ghcr.io/xilpanda/linuxspec-frontend
  newTag: ca20942
- name: ghcr.io/xilpanda/linuxspec-backend
  newTag: f9c27de
