apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: linuxspec-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-seed-store
    kind: ClusterSecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: backend-secrets-source
        property: MONGO_URI
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: backend-secrets-source
        property: ADMIN_API_KEY
    - secretKey: EMAIL
      remoteRef:
        key: backend-secrets-source
        property: EMAIL
    - secretKey: EMAIL_PASS
      remoteRef:
        key: backend-secrets-source
        property: EMAIL_PASS
