#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GATEKEEPER_DIR="$ROOT_DIR/k8s/security/gatekeeper"
FALCO_VALUES="$ROOT_DIR/k8s/security/falco/values.yaml"

echo "[1/5] Installing OPA Gatekeeper"
kubectl apply -f "https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.15/deploy/gatekeeper.yaml"
kubectl rollout status deployment/gatekeeper-controller-manager -n gatekeeper-system --timeout=180s

echo "[2/5] Applying Gatekeeper templates and constraints"
kubectl apply -f "$GATEKEEPER_DIR/template-deny-latest-tag.yaml"
kubectl apply -f "$GATEKEEPER_DIR/template-require-resources.yaml"
kubectl apply -f "$GATEKEEPER_DIR/template-deny-privileged.yaml"
kubectl apply -f "$GATEKEEPER_DIR/template-require-runasnonroot.yaml"

# Wait for CRDs generated by templates before applying constraints.
kubectl wait --for=condition=Established crd/k8sdenylatesttags.constraints.gatekeeper.sh --timeout=120s
kubectl wait --for=condition=Established crd/k8srequireresources.constraints.gatekeeper.sh --timeout=120s
kubectl wait --for=condition=Established crd/k8sdenyprivilegeds.constraints.gatekeeper.sh --timeout=120s
kubectl wait --for=condition=Established crd/k8srequirerunasnonroots.constraints.gatekeeper.sh --timeout=120s

kubectl apply -f "$GATEKEEPER_DIR/constraint-deny-latest-tag.yaml"
kubectl apply -f "$GATEKEEPER_DIR/constraint-require-resources.yaml"
kubectl apply -f "$GATEKEEPER_DIR/constraint-deny-privileged.yaml"
kubectl apply -f "$GATEKEEPER_DIR/constraint-require-runasnonroot.yaml"

echo "[3/5] Installing Falco Helm chart"
helm repo add falcosecurity "https://falcosecurity.github.io/charts" >/dev/null
helm repo update >/dev/null
helm upgrade --install falco falcosecurity/falco \
  --namespace falco \
  --create-namespace \
  -f "$FALCO_VALUES"

echo "[4/5] Waiting for Falco rollout"
kubectl rollout status daemonset/falco -n falco --timeout=240s

echo "[5/5] Runtime security components ready"
kubectl get pods -n gatekeeper-system
kubectl get pods -n falco
kubectl get k8sdenylatesttag.constraints.gatekeeper.sh
kubectl get k8srequireresources.constraints.gatekeeper.sh
kubectl get k8sdenyprivileged.constraints.gatekeeper.sh
kubectl get k8srequirerunasnonroot.constraints.gatekeeper.sh

echo "Done. DevSecOps runtime layer is installed."
